config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :posts
  devise_for :founders
  get 'about', to: 'pages#about'
  get 'product', to: 'pages#product'
  get 'admin_area', to: 'pages#admin'
end

app/models/founder.rb
class Founder < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: Founder
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

  def product

  end

  def admin

  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_founder!, only: [:edit, :update, :new, :destroy, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_founder

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    markdown.render(text).html_safe
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        %p.copyright.text-muted Copyright &copy; Lava 2015
    .row
      .text-right.text-muted
        = link_to "admin-area", admin_area_path, class: 'btn'

app/views/layouts/_intro_header.html.haml
.intro-header
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .site-heading
          = yield :site_heading

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top#navbar-custom
  .container
    .navbar-header.page-scroll
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
= link_to 'The Product', product_path, class: 'navbar-brand'
= link_to 'Blog', posts_path, class: 'navbar-brand'
= link_to 'About Us', about_path , class: 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Lava'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Lava'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  -#  fonts:
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  %body
    %header
      = render 'layouts/navigation'
      = render 'layouts/intro_header'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      =render 'layouts/footer'

app/views/pages/about.html.haml
= content_for :site_heading do
  %h1 Team
  %hr.small
  %span.subheading Improving the world

text

app/views/pages/admin.html.haml
= link_to 'Login', new_founder_session_path, class: 'btn btn-success'
= link_to 'Sign Up', new_founder_registration_path, class: 'btn btn-info'
= link_to 'Edit My User', edit_founder_registration_path, class: 'btn btn-info'
= link_to 'Logout', destroy_founder_session_path, method: 'delete', class: 'btn btn-danger'

%p There will be more stuff here, all the blog admin stuff too..

app/views/pages/product.html.haml
= content_for :site_heading do
  %h1 The Lavamaker
  %hr.small
  %span.subheading introducing a revolutionary way for you to recycle plastic

text

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|

  .form-inputs
    = f.input :title
    = f.input :body

  .form-actions
    = f.button :submit

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1.text-center Blog

.container
  - @posts.each do |post|
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .post-preview
          = link_to post do
            %h2
              = post.title
            %h4
              = truncate post.body, length: 300
            %p
              Posted by
              = post.author.username #TODO: Add link to all the user's posts
              on
              = post.created_at.localtime
.text-right
  = link_to 'New Post', new_post_path, class: 'btn'

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
= content_for :site_heading do
  %h1
    = @post.title
  %span By
  = @post.author.username # TODO: Add Link


.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1.post-body
      %h1
        = @post.title
      = markdown @post.body


= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

:javascript
  $(".intro-header").addClass("blog-image");

app/views/visitors/index.html.haml
= content_for :site_heading do
  %h1 Lava Maker
  %hr.small
  %span.subheading Melt -> Craft -> Restart

.row
  .col-sm-4
    %img.img-circle.img-responsive.img-center(src="http://placehold.it/300x300" alt="")
    %h2.text-center Recycling
    %p.text-justify Do your part to save the planet. Instead of throwing old plastic away, simply reuse it.
  .col-sm-4
    %img.img-circle.img-responsive.img-center{:alt => "", :src => "http://placehold.it/300x300"}
    %h2.text-center Ran out of filament?
    %p.text-justify Never again with !insert product name here! :P We really need a product name.
  .col-sm-4
    %img.img-circle.img-responsive.img-center{:alt => "", :src => "http://placehold.it/300x300"}
    %h2.text-center Save Money
    %p.text-justify And why can't you buy a tenth of a spool of filament? And don't even get me started on the shipping costs.